[platformio]
default_envs = esp32dev

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit ADS1X15@^2.4.0

[env:esp32dev]
board = esp32dev
build_flags =
    -DGRILL_BOARD_ESP32_CLASSIC

[env:esp32-s3-wroom]
board = esp32-s3-devkitc-1
build_flags =
    -DGRILL_BOARD_ESP32S3_WROOM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
